import { expect, test } from '@playwright/test'
test('phone sends the agreed contract and shows an answer', async ({ page }) => {
  await page.route('**/api/ask', async route => {
    expect(route.request().postDataJSON()).toEqual({ session_id: 'judge-01', text: 'What is this?' })
    await route.fulfill({ json: { display: 'A protein bar', speak: '', level: 'display', latency_ms: 120 } })
  })
  await page.goto('/phone')
  await page.getByLabel('OR TYPE A QUESTION').fill('What is this?')
  await page.getByRole('button', { name: 'Send question' }).click()
  await expect(page.getByText('A protein bar', { exact: true })).toBeVisible()
  await expect(page.getByText('Here’s what I found.')).toBeVisible()
})
test('phone recovers from a failed backend request', async ({ page }) => {
  await page.route('**/api/ask', route => route.fulfill({ status: 503 }))
  await page.goto('/phone')
  await page.getByLabel('OR TYPE A QUESTION').fill('Help')
  await page.getByRole('button', { name: 'Send question' }).click()
  await expect(page.getByRole('alert')).toContainText('brain is unavailable')
  await expect(page.getByRole('button', { name: 'Retry question' })).toBeEnabled()
})
test('mobile demo is clearly labeled and does not overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/phone')
  await page.getByRole('button', { name: 'More options' }).click()
  await page.getByLabel('Demo mode').check()
  await page.getByRole('button', { name: 'Close menu' }).click()
  await expect(page.getByText('DEMO MODE · Scripted examples', { exact: false })).toBeVisible()
  await page.getByLabel('OR TYPE A QUESTION').fill('What is this?')
  await page.getByRole('button', { name: 'Send question' }).click()
  await expect(page.getByText('Demo: 12g protein per bar', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/phone-mobile.png', fullPage: true })
})
